config/routes.rb
Rails.application.routes.draw do
  root "plans#index"
  resources :plans, only:[:index,:new,:create]
  resources :maps, only:[:new,:create]
  resources :streets, only:[:new,:create]
  resources :weathers, only:[:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plan.rb
class Plan < ApplicationRecord
  has_one :visit_place
end

app/models/visit_place.rb
class VisitPlace < ApplicationRecord
  belongs_to :plan
  geocoded_by :municipality
    after_validation :geocode, if: :municipality_changed?
end

app/models/visit_point.rb
class VisitPoint < ApplicationRecord
  belongs_to :visit_place
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth


  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  require 'bigdecimal'
  require 'bigdecimal/util' 
  def new
    @visit_place_id = flash[:visit_place_id]
    visit_placese = flash[:address]
    @visit_place = visit_placese["prefecture"]+visit_placese["municipality"]
    gon.visit_place = @visit_place
    gon.latlng = {lat: visit_placese["latitude"],lng: visit_placese["longitude"]}

    require 'net/https'
    require 'uri'
    require 'json'
    require 'nokogiri'

    api_key = ENV["GOOGLE_KEY"]
    lat = visit_placese["latitude"]
    lng = visit_placese["longitude"]
    rad = '5000'

    types = ["amusement_park","cafe","food","museum","place_of_worship","restaurant","spa","zoo"]

    language = 'ja'

    uri = URI.parse "https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=#{lat},#{lng}&radius=#{rad}&types=#{types}&sensor=false&language=ja&key=#{api_key}"

    request = Net::HTTP::Get.new(uri.request_uri)
    response = Net::HTTP.start(uri.host, uri.port, use_ssl: uri.scheme == 'https') do |http|
      http.request(request)
    end

    body = JSON.parse(response.body)
    results = body['results']
    @placese = []
    results.each do |info|
      if info["name"].nil? || info["photos"].nil?
        next
      end
      location = info["geometry"]["location"]
      location_lat = location["lat"]
      location_lng = location["lng"]
      location_point = [location_lat,location_lng]
      image_arr = info["photos"]
      image = image_arr[0]["photo_reference"]
      title = info["name"]
      uri = URI.parse "https://maps.googleapis.com/maps/api/place/photo?maxwidth=400&photoreference=#{image}&key=#{api_key}"
      request = Net::HTTP::Get.new(uri.request_uri)
      response = Net::HTTP.start(uri.host, uri.port, use_ssl: uri.scheme == 'https') do |http|
        http.request(request)
      end
      body = response.body
      file = Nokogiri::HTML(body)
      set = file.xpath('//a/@href')
      image_info = set[0]
      if image_info.nil?
        next
      end
      image_url = image_info.value
      place = [image_url,title,location_point]
      @placese.push(place)
    end
    if @placese.nil?
      redirect_to controller: :plans, action: :index
    end
    @visit_point = VisitPoint.new
  end
  
  def create
    visit_place_id = params["visit_point"][:visit_place_id]
    visit_points = visit_point_params
    visit_points.each_with_index do |point,i|
      point_arr = point.split(",")
      visit_lat = point_arr[0].delete("[").to_d
      visit_lng = point_arr[1].delete("]").strip.to_d
      visit_point_id = VisitPoint.create(latitude: visit_lat, longitude: visit_lng, visit_place_id: visit_place_id)
      if i == visit_points.length - 1
        flash.keep[:visit_place_id] = visit_point_id.visit_place_id
      end
    end
    redirect_to controller: :streets, action: :new
  end

  private
    def visit_point_params
      visit_param = params
      visit_param.delete("authenticity_token")
      visit_param.delete("commit")
      visit_param.delete("controller")
      visit_param.delete("action")
      visit_param.delete("visit_point")
      visit_location_index = visit_param.keys
      visit_points = []
      visit_location_index.each do |i|
        visit_points.push(visit_param[i])
      end
      return visit_points
    end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
    Rails.cache.clear
  end
  def new
    require 'securerandom'
    require 'flickraw'
    search_trip
    if @image_url == []
      search_trip
    end
    @plan = Plan.new
    flash.keep[:prefecture] = @prefecture
    flash.keep[:municipality] = @city_name
  end
  def create
    plan = Plan.create(plan_params)
    visit_place = VisitPlace.create(prefecture: flash[:prefecture], municipality: flash[:municipality],plan_id: plan.id)
    if visit_place.valid?
      flash.keep[:address] = visit_place
      flash.keep[:visit_place_id] = visit_place.id
      redirect_to controller: :maps, action: :new
    end
  end
  private
  def search_trip
    prefecture_num = SecureRandom.random_number(47)
    hoge = Prefecture.new
    huga = hoge.getName
    prefecture_hash = huga[prefecture_num-1]
    @prefecture = prefecture_hash[:name]
    
    params =URI.encode_www_form({prefCode:prefecture_num})
    uri = URI.parse("https://opendata.resas-portal.go.jp/api/v1/cities?#{params}")
    req = Net::HTTP::Get.new(uri.request_uri)
    req["X-API-KEY"] = ENV['RESAS_KEY']

    https = Net::HTTP.new(uri.host, uri.port)
    https.use_ssl = true
    res = https.request(req)

    res_body = JSON.parse(res.body)
    result = res_body["result"]
    city_num = SecureRandom.random_number(result.length)
    city_hash = result[city_num]
    @city_name = city_hash["cityName"]

    FlickRaw.api_key = ENV["FLICKR_KEY"]
    FlickRaw.shared_secret = ENV["FLICKR_SECRET_KEY"]
    images = flickr.photos.search(tags: @city_name, sort: "interestingness-desc", per_page: 4)
    @image_url = []
    images.each do |image|
      url = FlickRaw.url image
      @image_url.push(url)
    end
  end
  def plan_params
    params.require(:plan).permit(:name)
  end
end

app/controllers/streets_controller.rb
class StreetsController < ApplicationController
  def new
    points_info = VisitPoint.where(visit_place_id: flash[:visit_place_id])
    api_key = ENV["GOOGLE_KEY"]
    @uri = []
    @latlng = []
    points_info.each_with_index do |point,i|
      lat = point.latitude.to_f
      lng = point.longitude.to_f
      @uri.push("https://maps.googleapis.com/maps/api/streetview?size=640x640&location=#{lat},#{lng}&fov=120&pitch=0&key=#{api_key}")
      @latlng.push([lat,lng])
        if points_info.length-1 == i 
          weather_apikey = ENV["WEATHER_KEY"]
          city_lat = 
          uri = URI.parse "http://api.openweathermap.org/data/2.5/weather?lat=#{lat}&lon=#{lng}&appid=#{weather_apikey}&lang=ja&units=metric"

          request = Net::HTTP::Get.new(uri.request_uri)
          response = Net::HTTP.start(uri.host, uri.port, use_ssl: uri.scheme == 'https') do |http|
            http.request(request)
          end

          body = JSON.parse(response.body)
          @weather = body["weather"][0]["description"]
          @temp = body["main"]["temp"]
        end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/streets_helper.rb
module StreetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EasyVirtualTrip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.0.7/css/swiper.min.css" />
    <%= yield :css %>
    <%= include_gon %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/maps/new.html.erb
<div class="main-wrapper">
  <div class="top-content">
    <h1>行ってみたい場所にチェックを入れてください</h1>
  </div>
  <div class="form-contents">
    <%= form_with model:@visit_point,url:maps_path, local: true do |f|%>
      <div class="placese-contents">
        <%=f.hidden_field :visit_place_id, :value => @visit_place_id%>

        <% @placese.each_with_index do |item,i| %>
          <div class=place-item>
            <div>
              <img src=<%=item[0]%>>
            </div>
            <div class="place-name-wrap">
              <h2 class="place-name"><%= item[1]%></h2>
            </div>
            <div class="checkbox-content">
              <label>
              <input type="checkbox" class="checkbox-input" name=<%=i%> value="<%=item[2]%>"> 
              <span class="checkbox-parts">行きたい</span>
              </label>
            </div>
          </div>
        <% end %>

      </div>

      <div class="btn-wrap">
        <%=f.submit "決定",class:"submit"%>
      </div>

    <% end%>
  </div>
</div>
<% content_for :css do %>
  <%= stylesheet_link_tag 'place/new' %>
<% end %>

app/views/plans/index.html.erb
<div class="index-main">
  <div class="index-main-content">

    <div class="index-main-top">
      <p class="catch-title">Easy Virtual Trip</p>
      <p class="catch-title">*現在はGoogle APIの利用を中止しているため、正常に動作しません*</p>
      <p class="site-info">このサイトでは日本全国の市町村区をランダムに選出<br>そして選ばれた場所にある施設情報を表示します<br>中々旅行へ行けない昨今ですが 旅行の想像を手助けできればと思います</p>
    </div>

    <div class="trip-bottun">
      <%= link_to("Go to Here", new_plan_path, {class:"btn-border btn"}) %>
      <%= link_to("Go to Here", new_plan_path, {class:"btn-border btn"}) %>
      <%= link_to("Go to Here", new_plan_path, {class:"btn-border btn"}) %>
    </div>
  </div>
</div>
<script>
  if (window.name != "any") {
    location.reload();
    window.name = "any";
  } else {
    window.name = "";
  }
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r67/three.min.js"></script>
<%= javascript_pack_tag 'top/application' %>
<% content_for :css do %>
    <%= stylesheet_link_tag 'plan/index' %>
<% end %>

app/views/plans/new.html.erb
<div class="main-wrapper">
  <div class="top-contents">
    <div class="swiper-container">
      <div class="swiper-wrapper">
          <% @image_url.each do |url|%>
            <div class="swiper-slide" data-test-set="test" style="background-image:url(<%=url%>)">
              <%=image_tag url, class:"entity-img"%>
            </div>
          <%end%>
      </div>
      <div class="swiper-pagination"></div>

      <div class="swiper-button-prev"></div>
      <div class="swiper-button-next"></div>

      <div class="swiper-scrollbar"></div>
    </div>
  </div>




  <div class="bottom-contents">
    <div class="city-name">
      <h2 class="city-name-text"><%= @city_name%></h2>
    </div>
    <div class="button-contents">
      <div class="again">
        <%= link_to("もう一度選ぶ", new_plan_path ,{class:"btn2-border btn2"})%>
      </div>
      <div class="send-contents">
        <%=form_with model:@plan do |f|%>
          <%=f.hidden_field :name, :value => @city_name%>
          <a class="btn2 btn2-border" id="submit-wrap"><%=f.submit "#{@city_name}で決定",id:"submit"%></a>
        <%end%>
      </div>
    </div>
  </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.0.7/js/swiper.min.js"></script>
<% content_for :css do %>
  <%= stylesheet_link_tag 'plan/new' %>
<% end %>
<%= javascript_pack_tag 'plan/application' %>

app/views/streets/new.html.erb
<div class="main-wrapper">
  <div class="link-wrap">
    <%= link_to("トップページへ戻る", root_path ,{class:"btn2-border btn2"})%>
  </div>
  <div class="weather-wrap">
    <h3>現地の天気（現在）</h3>
    <h4><%=@weather%></h4>
    <h4><%=@temp%>度</h4>
  </div>

  <div class="photo-wrap">
    <div class="swiper-container main-slider loading">
      <div class="swiper-wrapper">

        <%@uri.each_with_index do |u,i|%>
          <div class="swiper-slide">
            <figure class="slide-bgimg" style="background-image:url(<%=u%>)">
              <img src=<%=u%> class="entity-img" />
            </figure>
            <div class="content">
              <p class="title"><%=@latlng[i]%></p>
              <span class="caption">実際のストリートビューは上記の緯度経度を参考にgoogle mapよりご覧ください</span>
            </div>
          </div>
        <% end %>

      </div>

      <div class="swiper-button-prev swiper-button-white"></div>
      <div class="swiper-button-next swiper-button-white"></div>
    </div>

    <div class="swiper-container nav-slider loading">
      <div class="swiper-wrapper" role="navigation">
        <%@uri.each do |u|%>
          <div class="swiper-slide">
            <figure class="slide-bgimg" style="background-image:url(<%=u%>)">
              <img src=<%=u%> class="entity-img" />
            </figure>
            <div class="content">
              <p class="title"></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.0.7/js/swiper.min.js"></script>

<% content_for :css do %>
  <%= stylesheet_link_tag 'street/new' %>
<% end %>
<%= javascript_pack_tag 'street/application' %>